FROM python:3.8
COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt
COPY kafka/producer-shorttime.py /app/producer-shorttime.py
WORKDIR /app

CMD ["python", "producer-shorttime.py"]

