FROM python:3.8
COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt
COPY kafka/producer-longtime.py /app/producer-longtime.py
WORKDIR /app

CMD ["python", "producer-longtime.py"]

